2025-06-24 06:30:18,530 - 7044 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 06:30:18,638 - 7044 - WARNING - [run_bot_process] - A 'python-telegram-bot' csomag nincs telepítve, a bot nem indul el.
2025-06-24 06:39:11,552 - 15280 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 06:39:11,664 - 15280 - WARNING - [run_bot_process] - A 'python-telegram-bot' csomag nincs telepítve, a bot nem indul el.
2025-06-24 06:52:13,555 - 11804 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 06:52:13,671 - 11804 - WARNING - [run_bot_process] - A 'python-telegram-bot' csomag nincs telepítve, a bot nem indul el.
2025-06-24 06:54:55,866 - 10848 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 06:54:55,978 - 10848 - WARNING - [run_bot_process] - A 'python-telegram-bot' csomag nincs telepítve, a bot nem indul el.
2025-06-24 07:00:15,326 - 15068 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 07:00:18,470 - 15068 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 07:00:18,473 - 15068 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 494, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 42, in __init__
    self.app = self.Application.builder().token(self.token).build()
               ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 459, in builder
    return ApplicationBuilder()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_applicationbuilder.py", line 205, in __init__
    self._job_queue: ODVInput[JobQueue] = DefaultValue(JobQueue())
                                                       ~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 07:07:23,117 - 12680 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 07:07:24,521 - 12680 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 07:07:24,522 - 12680 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 494, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 42, in __init__
    self.app = self.Application.builder().token(self.token).build()
               ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 459, in builder
    return ApplicationBuilder()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_applicationbuilder.py", line 205, in __init__
    self._job_queue: ODVInput[JobQueue] = DefaultValue(JobQueue())
                                                       ~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 07:13:29,524 - 11228 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 07:13:30,956 - 11228 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 07:13:30,958 - 11228 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 494, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 42, in __init__
    self.app = self.Application.builder().token(self.token).build()
               ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 459, in builder
    return ApplicationBuilder()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_applicationbuilder.py", line 205, in __init__
    self._job_queue: ODVInput[JobQueue] = DefaultValue(JobQueue())
                                                       ~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 07:18:44,068 - 12232 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 07:18:45,466 - 12232 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 07:18:45,468 - 12232 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 494, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 42, in __init__
    self.app = self.Application.builder().token(self.token).build()
               ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 459, in builder
    return ApplicationBuilder()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_applicationbuilder.py", line 205, in __init__
    self._job_queue: ODVInput[JobQueue] = DefaultValue(JobQueue())
                                                       ~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 07:25:48,581 - 12688 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 07:25:48,982 - 12688 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 07:25:48,983 - 12688 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 509, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 47, in __init__
    job_queue = JobQueue()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 07:32:37,864 - 1648 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 07:32:38,278 - 1648 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 07:32:39,190 - 1648 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: 'Updater' object has no attribute '_Updater__polling_cleanup_cb' and no __dict__ for setting new attributes
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 509, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 55, in __init__
    .build()
     ~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_applicationbuilder.py", line 312, in build
    updater = Updater(bot=bot, update_queue=update_queue)
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 128, in __init__
    self.__polling_cleanup_cb: Optional[Callable[[], Coroutine[Any, Any, None]]] = None
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Updater' object has no attribute '_Updater__polling_cleanup_cb' and no __dict__ for setting new attributes
2025-06-24 07:47:47,804 - 12500 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 07:47:48,223 - 12500 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 07:47:49,119 - 12500 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: 'Updater' object has no attribute '_Updater__polling_cleanup_cb' and no __dict__ for setting new attributes
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 509, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 55, in __init__
    .build()
     ~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_applicationbuilder.py", line 312, in build
    updater = Updater(bot=bot, update_queue=update_queue)
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_updater.py", line 128, in __init__
    self.__polling_cleanup_cb: Optional[Callable[[], Coroutine[Any, Any, None]]] = None
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Updater' object has no attribute '_Updater__polling_cleanup_cb' and no __dict__ for setting new attributes
2025-06-24 08:01:02,506 - 2636 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 08:01:02,923 - 2636 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 08:01:02,925 - 2636 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 509, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 47, in __init__
    job_queue = JobQueue()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 08:09:57,311 - 3288 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 08:09:57,730 - 3288 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 08:09:57,732 - 3288 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 506, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 47, in __init__
    job_queue = JobQueue()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 08:12:24,386 - 1456 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 08:12:25,743 - 1456 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 08:12:25,744 - 1456 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 494, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 42, in __init__
    self.app = self.Application.builder().token(self.token).build()
               ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 459, in builder
    return ApplicationBuilder()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_applicationbuilder.py", line 205, in __init__
    self._job_queue: ODVInput[JobQueue] = DefaultValue(JobQueue())
                                                       ~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 08:13:35,060 - 13844 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 08:13:36,407 - 13844 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 08:13:36,408 - 13844 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 494, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 42, in __init__
    self.app = self.Application.builder().token(self.token).build()
               ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_application.py", line 459, in builder
    return ApplicationBuilder()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_applicationbuilder.py", line 205, in __init__
    self._job_queue: ODVInput[JobQueue] = DefaultValue(JobQueue())
                                                       ~~~~~~~~^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 08:18:24,746 - 13852 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 08:18:25,372 - 13852 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 08:18:25,373 - 13852 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 187, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 46, in __init__
    job_queue = JobQueue()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 08:20:30,547 - 10776 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 08:20:30,966 - 10776 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 08:20:30,968 - 10776 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: Only timezones from the pytz library are supported
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 187, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 46, in __init__
    job_queue = JobQueue()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 112, in __init__
    self.scheduler: "AsyncIOScheduler" = AsyncIOScheduler(  # noqa: UP037
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
        **self.scheduler_configuration
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 87, in __init__
    self.configure(gconfig, **options)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 126, in configure
    self._configure(config)
    ~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\asyncio.py", line 48, in _configure
    super(AsyncIOScheduler, self)._configure(config)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\schedulers\base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
                    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\apscheduler\util.py", line 93, in astimezone
    raise TypeError('Only timezones from the pytz library are supported')
TypeError: Only timezones from the pytz library are supported
2025-06-24 09:33:02,234 - 14712 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 09:33:03,610 - 14712 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: To use `JobQueue`, PTB must be installed via `pip install "python-telegram-bot[job-queue]"`.
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 187, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 46, in __init__
    job_queue = JobQueue()
  File "C:\Users\milan\AppData\Local\Programs\Python\Python313\Lib\site-packages\telegram\ext\_jobqueue.py", line 105, in __init__
    raise RuntimeError(
    ...<2 lines>...
    )
RuntimeError: To use `JobQueue`, PTB must be installed via `pip install "python-telegram-bot[job-queue]"`.
2025-06-24 09:47:59,261 - 8548 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 09:48:00,746 - 8548 - CRITICAL - [run_bot_process] - A Telegram bot processz hiba miatt leállt: 'TelegramBotManager' object has no attribute 'select_account'
Traceback (most recent call last):
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 187, in run_bot_process
    bot_manager = TelegramBotManager(token=token, config=config, data_dir=data_dir, telegram_classes=telegram_classes)
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 57, in __init__
    self._register_handlers()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\milan\Desktop\Copytrader\modules\telegram_bot.py", line 63, in _register_handlers
    self.SELECT_ACCOUNT: [self.CallbackQueryHandler(self.select_account, pattern='^account_')],
                                                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'TelegramBotManager' object has no attribute 'select_account'
2025-06-24 09:55:09,236 - 932 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 09:55:11,272 - 932 - INFO - [run] - Telegram bot processz indul...
2025-06-24 09:55:11,273 - 932 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 09:55:11,746 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:11,947 - 932 - INFO - [pnl_command] - /pnl parancs fogadva.
2025-06-24 09:55:12,107 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:12,283 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:12,480 - 932 - INFO - [pnl_command] - /pnl parancs fogadva.
2025-06-24 09:55:12,636 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:12,780 - 932 - INFO - [pnl_command] - /pnl parancs fogadva.
2025-06-24 09:55:12,929 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:13,072 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:13,242 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:13,387 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:13,566 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:13,776 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:13,948 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:14,094 - 932 - INFO - [pnl_command] - /pnl parancs fogadva.
2025-06-24 09:55:14,438 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:14,598 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:14,745 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:14,901 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:15,074 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:15,234 - 932 - INFO - [pnl_command] - /pnl parancs fogadva.
2025-06-24 09:55:15,377 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:15,515 - 932 - INFO - [pnl_command] - /pnl parancs fogadva.
2025-06-24 09:55:15,767 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:15,920 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:16,057 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 09:55:16,257 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 10:01:04,567 - 932 - INFO - [status_command] - /status parancs fogadva.
2025-06-24 10:01:16,695 - 932 - INFO - [pnl_command] - /pnl parancs fogadva.
2025-06-24 10:32:17,861 - 2028 - INFO - [setup_logging] - Naplózás beállítva a(z) 'Process-1' processz számára. Szint: DEBUG. Fájl: C:\Users\milan\Desktop\Copytrader\data\logs\telegram_bot_process.txt
2025-06-24 10:32:19,916 - 2028 - INFO - [run] - Telegram bot processz indul...
2025-06-24 10:32:19,917 - 2028 - DEBUG - [__init__] - Using proactor: IocpProactor
2025-06-24 10:35:23,916 - 2028 - INFO - [status_command] - /status parancs fogadva.
